Repository AnyCase-Company-LTD/NugetAnalyzer, pull requests merged in 2019-05, with the labels that each got.

#29 Layout creation (#18)
  .gitignore
  NugetAnalyzer/Controllers/HomeController.cs
  NugetAnalyzer/NugetAnalyzer.csproj
  NugetAnalyzer/Startup.cs
  NugetAnalyzer/Views/Home/Index.cshtml
  NugetAnalyzer/Views/Shared/_Layout.cshtml
  NugetAnalyzer/Views/_ViewImports.cshtml
  NugetAnalyzer/Views/_ViewStart.cshtml
  NugetAnalyzer/compilerconfig.json
  NugetAnalyzer/compilerconfig.json.defaults
  NugetAnalyzer/wwwroot/images/icon.jpg
  NugetAnalyzer/wwwroot/images/logo/logo.ico
  NugetAnalyzer/wwwroot/scripts/bootstrap.min.js
  NugetAnalyzer/wwwroot/scripts/bootstrap.min.js.map
  NugetAnalyzer/wwwroot/scripts/jquery-3.4.0.min.js
  NugetAnalyzer/wwwroot/scripts/popper.min.js
  NugetAnalyzer/wwwroot/stylesheets/Home/Home.scss
  NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.scss
  NugetAnalyzer/wwwroot/stylesheets/bootstrap.min.css
  NugetAnalyzer/wwwroot/stylesheets/bootstrap.min.css.map
  azure-pipelines.yml
Labels: enhancement, front-end

#37 Implement git service (#23)
  NugetAnalyzer.BLL/Interfaces/IGitService.cs
  NugetAnalyzer.BLL/NugetAnalyzer.BLL.csproj
  NugetAnalyzer.BLL/Services/GitService.cs
Labels: back-end, enhancement

#45 Renamed report models in the whole solution
  NugetAnalyzer.BLL.Test/Services/RepositoryServiceTests.cs
  NugetAnalyzer.BLL/Interfaces/IRepositoryService.cs
  NugetAnalyzer.BLL/Services/RepositoryService.cs
  NugetAnalyzer.Dtos/Converters/ProjectConverter.cs
  NugetAnalyzer.Dtos/Converters/RepositoryConverter.cs
  NugetAnalyzer.Dtos/Converters/SolutionConverter.cs
  NugetAnalyzer.Dtos/Models/Reports/ProjectVersionReport.cs
  NugetAnalyzer.Dtos/Models/Reports/RepositoryVersionReport.cs
  NugetAnalyzer.Dtos/Models/Reports/SolutionVersionReport.cs
Labels: fixes

#40 Create error views (#39)
  NugetAnalyzer.Web/Controllers/ErrorController.cs
  NugetAnalyzer.Web/Controllers/HomeController.cs
  NugetAnalyzer.Web/Middleware/ExceptionHandlingMiddleware.cs
  NugetAnalyzer.Web/NugetAnalyzer.Web.csproj
  NugetAnalyzer.Web/Startup.cs
  NugetAnalyzer.Web/Views/Error/NotFoundError.cshtml
  NugetAnalyzer.Web/Views/Error/ServerError.cshtml
  NugetAnalyzer.Web/Views/Home/About.cshtml
  NugetAnalyzer.Web/Views/Home/Contacts.cshtml
  NugetAnalyzer.Web/compilerconfig.json
  NugetAnalyzer.Web/wwwroot/stylesheets/Home/Index.scss
Labels: back-end, enhancement, front-end

#33 Implement repository service (#22)
  NugetAnalyzer.BLL.Test/NugetAnalyzer.BLL.Test.csproj
  NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
  NugetAnalyzer.BLL.Test/Services/RepositorySaverServiceTests.cs
  NugetAnalyzer.BLL/Interfaces/IRepositoryAnalyzerService.cs
  NugetAnalyzer.BLL/Interfaces/IRepositorySaverService.cs
  NugetAnalyzer.BLL/Models/BaseRepositoryModel.cs
  NugetAnalyzer.BLL/Models/Packages/Package.cs
  NugetAnalyzer.BLL/Models/Projects/Project.cs
  NugetAnalyzer.BLL/Models/Repositories/Repository.cs
  NugetAnalyzer.BLL/Models/Solutions/Solution.cs
  NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
  NugetAnalyzer.BLL/Services/RepositorySaverService.cs
  NugetAnalyzer.Common/Interfaces/IDirectoryService.cs
  NugetAnalyzer.Common/Interfaces/IFileService.cs
  NugetAnalyzer.Common/Services/DirectoryService.cs
  NugetAnalyzer.Common/Services/FileService.cs
  NugetAnalyzer.Domain/Package.cs
  NugetAnalyzer.Domain/Project.cs
  NugetAnalyzer.Domain/Repository.cs
  NugetAnalyzer.Domain/Solution.cs
  NugetAnalyzer.Web.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  NugetAnalyzer.Web/Startup.cs
  NugetAnalyzer.Web/TagHelpers/CustomLogoTagHelper.cs
  NugetAnalyzer.Web/Views/Home/Index.cshtml
  NugetAnalyzer.Web/Views/Shared/_Layout.cshtml
  NugetAnalyzer.Web/Views/_ViewImports.cshtml
  NugetAnalyzer.Web/wwwroot/stylesheets/Home/Index.scss
  NugetAnalyzer.Web/wwwroot/stylesheets/Shared/_Layout.scss
  README.md
Labels: back-end, enhancement

#53 Corrected a logging and exception handling
  NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
  NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
  NugetAnalyzer.BLL/Services/NugetApiService.cs
  NugetAnalyzer.BLL/Services/NugetService.cs
  NugetAnalyzer.Web/Controllers/ErrorController.cs
  NugetAnalyzer.Web/Controllers/HomeController.cs
  NugetAnalyzer.Web/Middleware/ExceptionHandlingMiddleware.cs
  NugetAnalyzer.Web/Startup.cs
  NugetAnalyzer.Web/nlog.config
Labels: back-end, enhancement, fixes
